import Head from 'next/head';
import { ReactNode } from 'react';
import Header from './Header';

type LayoutProps = { children: ReactNode };

export function Layout({ children }: LayoutProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>{children}</main>
    </>
  );
}
